// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheets.Models;

#nullable disable

namespace TimeSheets.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251226181621_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeSheets.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            HasProjector = true,
                            Name = "A101"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            HasProjector = false,
                            Name = "B202"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            HasProjector = true,
                            Name = "C303"
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StudentGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1A",
                            StudentCount = 28
                        },
                        new
                        {
                            Id = 2,
                            Name = "2B",
                            StudentCount = 24
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Programming",
                            Type = 1
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Smith",
                            Salary = 45000f
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Anna Novak",
                            Salary = 48000f
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Peter Johnson",
                            Salary = 43000f
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            TeacherId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            TeacherId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            TeacherId = 3,
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.TimetableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TimetableEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            EndTime = new DateTime(2025, 3, 10, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentGroupId = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 3,
                            EndTime = new DateTime(2025, 3, 10, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 3, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentGroupId = 2,
                            SubjectId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 2,
                            EndTime = new DateTime(2025, 3, 11, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 3, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentGroupId = 1,
                            SubjectId = 2,
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("TimeSheets.Models.Views.ClassroomUsageView", b =>
                {
                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_ClassroomUsage", (string)null);
                });

            modelBuilder.Entity("TimeSheets.Models.Views.TeacherLoadView", b =>
                {
                    b.Property<DateTime>("FirstLesson")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLesson")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_TeacherLoad", (string)null);
                });

            modelBuilder.Entity("TimeSheets.Models.TeacherSubject", b =>
                {
                    b.HasOne("TimeSheets.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheets.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TimeSheets.Models.TimetableEntry", b =>
                {
                    b.HasOne("TimeSheets.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheets.Models.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheets.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeSheets.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("StudentGroup");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TimeSheets.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("TimeSheets.Models.Teacher", b =>
                {
                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
